//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your URL is invalid. Please check the formatting on it..
        /// </summary>
        internal static string Application_BearerAuthentication_InvalidURLException {
            get {
                return ResourceManager.GetString("Application_BearerAuthentication_InvalidURLException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unreachable. Please make sure it is up and running!.
        /// </summary>
        internal static string Application_BearerAuthentication_ServerUnreachableException {
            get {
                return ResourceManager.GetString("Application_BearerAuthentication_ServerUnreachableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while communicating with the server. Please try again..
        /// </summary>
        internal static string Application_BearerAuthentication_SomethingWrongException {
            get {
                return ResourceManager.GetString("Application_BearerAuthentication_SomethingWrongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL..
        /// </summary>
        internal static string Application_CreateClient_InvalidURLException {
            get {
                return ResourceManager.GetString("Application_CreateClient_InvalidURLException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unreachable..
        /// </summary>
        internal static string Application_CreateClient_ServerUnreachableException {
            get {
                return ResourceManager.GetString("Application_CreateClient_ServerUnreachableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected authentication scheme is unknown. Please choose one of the following: {0}.
        /// </summary>
        internal static string Application_InitializeAsync_UnknownAuthSchemeException {
            get {
                return ResourceManager.GetString("Application_InitializeAsync_UnknownAuthSchemeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 Bad Request: The server didn&apos;t like that call. Please check your syntax..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_400 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401 Unauthorized: The server doesn&apos;t recognize you. Please check your credentials..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_401 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 Forbidden: The server recognizes you, but is refusing access. Please ensure that you have permission to access this resource..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_403 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Not Found: The server is there, but the page you&apos;re going for is not. Please ensure that all required setup is complete..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_404 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 405 Not Allowed: The server recognizes your request, but is refusing it. Please check that all prerequisites for this request have been completed..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_405 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 408 Timeout: The server gave it a shot, but took too long and timed out. Please try again..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_408 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 410 Gone: Whatever was once at this location is gone now. Please contact the activity creator to look into this..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_410 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 413 Too Large: Your payload is too large for the server to handle. Please reduce its size or send it in batches..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_413 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 414 Too Long: Your URL is too long. Please shorten it if possible..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_414 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 415 Bad Payload Type: Your payload is in a format the server doesn&apos;t like. Please check the desired format (e.g. JSON, XML, etc)..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_415 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Server Error: Something went wrong on the server&apos;s side. Please try again..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_500 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501 Not Implemented: This version of the server doesn&apos;t have the method you&apos;re trying to invoke. Please check for available updates..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_501 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 502 Bad Gateway: Something went wrong on the server&apos;s side. Please try again..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_502 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 Unavailable: The server is temporarily overloaded and can&apos;t process your request. Please try again in a bit..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_503 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 504 Timeout: The server gave it a shot, but took too long and timed out. Please try again..
        /// </summary>
        internal static string HTTPMagic_CheckStatus_504 {
            get {
                return ResourceManager.GetString("HTTPMagic_CheckStatus_504", resourceCulture);
            }
        }
    }
}
